server:
  port: 2020

# spring data
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jrtp
    username: root
    password: 4562
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



